Modules/Programs/Entities/Program.php
<?php

namespace Modules\Programs\Entities;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Modules\Media\Support\Traits\MediaRelation;
use Modules\Programs\Entities\Traits\Featurable;
use Modules\Programs\Entities\Traits\Typeable;

class Program extends Model
{
    use Translatable, Featurable, Typeable, MediaRelation;

    protected $table = 'programs__programs';
    public $translatedAttributes = [
        'name',
        'description',
        'lessons_schedule',
        'narrator',
        'max_group',
        'phone',
        'price',
        'guide_caption',
        'category',
        'order'
    ];
    protected $fillable = [
        'name',
        'description',
        'max_group',
        'lessons_count',
        'lessons_schedule',
        'duration',
        'phone',
        'narrator',
        'dates',
        'price',
        'type_id',
        'guide_caption',
        'category'
    ];

    public $casts = [
        'dates' => 'array'
    ];

    public function getDatesOrderedAttribute()
    {
        return collect($this['dates'])->sort()->values()->all();
    }

    public function getFormDatesAttribute()
    {
        return $this['dates'] ? array_combine($this['dates'], $this['dates']) : [];
    }

    public function getFormattedTextAttribute()
    {
        $text = str_replace("\n", '</p><p>', $this['description']);

        return '<p>' . $text . '</p>';
    }

    public function images()
    {
        return $this->files()->where('zone', 'programImage');
    }

    public function pdf()
    {
        return $this->files()->where('zone', 'programPdf');
    }

}

Modules/Programs/Entities/Type.php
<?php

namespace Modules\Programs\Entities;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Modules\Page\Entities\Page;
use Modules\Programs\Entities\Traits\Activateable;

class Type extends Model
{
    use Translatable, Activateable;

    protected $table = 'programs__types';
    public $translatedAttributes = [
        'name',
        'program_description',
        'excursion_description'
    ];
    protected $fillable = [
        'name',
        'active',
        'program_description',
        'excursion_description',
        'page_id'
    ];

    public function page()
    {
        return $this->belongsTo(Page::class);
    }

    protected function format($value)
    {
        $text = str_replace("\n", '</p><p>', $value);

        return '<p>' . $text . '</p>';
    }

    public function getExcursionFormattedAttribute()
    {
        return $this->format($this['excursion_description']);
    }

    public function getProgramFormattedAttribute()
    {
        return $this->format($this['program_description']);
    }
}

Modules/Programs/Resources/views/frontend/items.blade.php
@foreach($items as $item)
    <div class="programs_item bg_color font_color">
        <div class="row">
            <div class="col-12 col-lg-6">
                <div class="programs_slider_container">
                    <div class="programs_slider" data-slider role="region" aria-label="слайдер">
                        @foreach($item->images as $k => $slide)
                            <div class="programs_slider_it" aria-live="polite" aria-label="{{ $k + 1 }} слайд із {{ $item->files->count() }} ">
                                <img src="{!! $slide->path !!}" alt="{{ $slide->alt_attribute }}">
                            </div>
                        @endforeach
                    </div>
                    <div class="slider_btn_container type1">
                        <div class="btn_pause bg_color font_color active" tabindex="-1" title="призупинити слайдер" aria-label="зупинити слайдер" role="button" id="btn_pause">
                            <span class="icon-iconfinder_icon-pause_211871"></span>
                        </div>
                        <div class="btn_play bg_color font_color active" tabindex="-1" title="увімкнути слайдер" aria-label="програти слайдер" role="button" id="btn_play">
                            <span class="icon-iconfinder_icon-play_211876"></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-12 col-lg-6">
                <div class="programs_info_container">
                    <div class="programs_info_title">
                        <h2>{{ $item->name }}</h2>
                    </div>
                    <div class="programs_info_text" style="text-indent: 20px; text-align: justify;">
                        {!! $item->formatted_text !!}
                    </div>

                    <div class="icons_container">
                        @foreach($item->features as $feature)
                            <div class="icons_item mod1 bg_color font_color" title="{{$feature->name}}" aria-label="{{$feature->name}}">
                                <img src="{!! $feature->icon !!}" alt="{{$feature->name}}">
                            </div>
                        @endforeach
                    </div>

                    <div class="programs_info_list">
                        <ul>
                            @if($item->dates)
                            <li>
                                <div class="programs_select_container">
                                    <span class="icon-calendar list_icon font_color"></span>
                                    <label for="inputState"><b>{{trans('programs::programs.frontend.dates')}}:</b></label>
                                    <div class="select_container font_color">
                                        <select id="inputState" aria-label="вибір дати" class="form-control programs_select bg_color font_color">
                                            @foreach(($item->dates_ordered ?? []) as $val)
                                                <option selected value="{{ $val }}" aria-label="{{ $val }}">{{ $val }}</option>
                                            @endforeach
                                        </select>
                                        <span class="icon-arrow_down"></span>
                                    </div>
                                </div>
                            </li>
                            @endif
                            @if ($item->category)
                                <li>
                                    <span class="icon-cart list_icon font_color"></span>
                                    <p><b>{{ trans('programs::programs.frontend.category') }}:</b> {{$item->category}}</p>
                                </li>
                            @endif
                            <li>
                                <span class="icon-user list_icon font_color"></span>
                                <p><b>{{trans('programs::programs.frontend.max_group')}}:</b>{{$item->max_group}}</p>
                            </li>
                            @if($item->lessons_count)
                                <li>
                                    <span class="icon-grid list_icon font_color"></span>
                                    <p><b>{{trans('programs::programs.frontend.lessons_count')}}:</b> {{$item->lessons_count}}</p>
                                </li>
                            @endif
                            @if(isset($item->lessons_schedule))
                                <li>
                                    <span class="icon-clock2 list_icon font_color"></span>
                                    <p><b>{{trans('programs::programs.frontend.lessons_schedule')}}:</b> {{$item->lessons_schedule}}</p>
                                </li>
                            @else
                                <li>
                                    <span class="icon-clock2 list_icon font_color"></span>
                                    <p><b>{{trans('programs::programs.frontend.time')}}:</b> {{$item->time}}</p>
                                </li>
                            @endif
                            <li>
                                <span class="icon-glass list_icon font_color"></span>
                                <p><b>{{trans('programs::programs.frontend.duration')}}:</b> {{$item->duration}}</p>
                            </li>
                            <li>
                                <span class="icon-phohe2 list_icon font_color"></span>
                                <p><b>{{trans('programs::programs.frontend.phone')}}:</b> {{$item->phone}}</p>
                            </li>
                            @if(isset($item->narrator))
                                <li>
                                    <span class="icon-users list_icon font_color"></span>
                                    <p><b>{{$item->guide_caption}}:</b> {{$item->narrator}}</p>
                                </li>
                            @else
                                <li>
                                    <span class="icon-users list_icon font_color"></span>
                                    <p><b>{{$item->guide_caption}}:</b> {{$item->guide}}</p>
                                </li>
                            @endif
                        </ul>
                    </div>

                    <div class="programs_info_price">
                        <h3>{{$item->price}}</h3>
                        <a href="#" role="button" data-toggle="modal" data-target="#modal2"
                           onclick="$('#modal2 input[name=\'program_id\']').val('{{$item->id}}')"
                           title="Надіслати запит" class="programs_btn programs_btn_info bg_color font_color" aria-label="{{trans('programs::programs.frontend.leave_request')}}">{{trans('programs::programs.frontend.leave_request')}}</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endforeach

Modules/Programs/Resources/views/frontend/programs-tabs.blade.php
<div class="store_head type1 font_color bg_color">
    <div class="content_container">
        <ul class="nav nav-pills nav_store nav-program mb-3" id="pills-tab" role="tablist">
            @foreach($types as $type)
                <li class="tab-item type2 font_color">
                    <a class="tab-link type1 {{ $currentType->id == $type->id ? 'active' : '' }}"
                       id="pills-tab-{{$type->page_id}}" title="{{ $type->name  }}" aria-label="{{ $type->name }}"
                       href="{{ route('page', $type->page->slug) }}" role="tab" aria-controls="pills-home" aria-selected="true">{{ $type->name }}</a>
                </li>
            @endforeach
        </ul>
    </div>
</div>

<section>
    <div class="programs_container">
        <div class="programs_container_top">
            <div class="content_container">
                <div class="work_text mod1 font_color">
                    <form action="">
                        <div class="programs_radio">
                            <div class="radio_it">
                                <input type="radio" name="kind" id="excursions" value="excursions" class="radio_input" aria-label="Екскурсії">
                                <label for="excursions">{{ trans('programs::programs.frontend.excursions') }}</label>
                            </div>
                            <div class="radio_it">
                                <input type="radio" name="kind" id="programs" value="programs" class="radio_input" aria-label="Програми" checked>
                                <label for="programs">{{ trans('programs::programs.frontend.programs') }}</label>
                            </div>
                        </div>
                    </form>
                    <div id="excursionsText" style="display: none; text-indent: 20px;">{!! $currentType->excursion_formatted !!}</div>
                    <div id="programsText" style="text-indent: 20px;">{!! $currentType->program_formatted !!}</div>
                </div>
            </div>
        </div>


        <div class="programs_body_container bg_color">
            <div class="content_container">
                <div id="excursionsTab" class="pseudo-tab" style="display: none;">
                    @include('programs::frontend.items', ['items' => $excursions])
                </div>
                <div id="programsTab" class="pseudo-tab">
                    @include('programs::frontend.items', ['items' => $programs])
                </div>
            </div>
        </div>
    </div>
</section>