Modules/Programs/Entities/Excursion.php
<?php

namespace Modules\Programs\Entities;

use Dimsav\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Modules\Media\Support\Traits\MediaRelation;
use Modules\Programs\Entities\Traits\Featurable;
use Modules\Programs\Entities\Traits\Typeable;

class Excursion extends Model
{
    use Translatable, Featurable, Typeable, MediaRelation;

    protected $table = 'programs__excursions';
    public $translatedAttributes = [
        'name',
        'description',
        'guide',
        'max_group',
        'phone',
        'price',
        'guide_caption',
        'category',
        'order'
    ];
    protected $fillable = [
        'name',
        'description',
        'max_group',
        'time',
        'duration',
        'phone',
        'guide',
        'dates',
        'price',
        'type_id',
        'category',
        'guide_caption'
    ];
    public $casts = [
        'dates' => 'array'
    ];

    public function getDatesOrderedAttribute()
    {
        return collect($this['dates'])->sort()->values()->all();
    }

    public function getFormDatesAttribute()
    {
        return $this['dates'] ? array_combine($this['dates'], $this['dates']) : [];
    }

    public function getFormattedTextAttribute()
    {
        $text = str_replace("\n", '</p><p>', $this['description']);

        return '<p>' . $text . '</p>';
    }

    public function images()
    {
        return $this->files()->where('zone', 'excursionImage');
    }

    public function pdf()
    {
        return $this->files()->where('zone', 'excursionPdf');
    }
}

Modules/Programs/Http/Controllers/Admin/ExcursionController.php
<?php

namespace Modules\Programs\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Modules\Programs\Entities\Excursion;
use Modules\Programs\Http\Requests\CreateExcursionRequest;
use Modules\Programs\Http\Requests\UpdateExcursionRequest;
use Modules\Programs\Repositories\ExcursionRepository;
use Modules\Core\Http\Controllers\Admin\AdminBaseController;
use Modules\Programs\Repositories\FeatureRepository;
use Modules\Programs\Repositories\TypeRepository;

class ExcursionController extends AdminBaseController
{
    /**
     * @var ExcursionRepository
     */
    private $excursion;
    /**
     * @var FeatureRepository
     */
    private $feature;
    /**
     * @var TypeRepository
     */
    private $type;

    public function __construct(ExcursionRepository $excursion, FeatureRepository $feature, TypeRepository $type)
    {
        parent::__construct();

        $this->excursion = $excursion;
        $this->feature = $feature;
        $this->type = $type;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $excursions = $this->excursion->all();

        return view('programs::admin.excursions.index', compact('excursions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $types = $this->type->all()->pluck('name', 'id')->toArray();
        $features = $this->feature->all()->pluck('name', 'id')->toArray();
        return view('programs::admin.excursions.create', compact('types', 'features'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateExcursionRequest $request
     * @return Response
     */
    public function store(CreateExcursionRequest $request)
    {
        $this->excursion->create($request->all());

        return redirect()->route('admin.programs.excursion.index')
            ->withSuccess(trans('core::core.messages.resource created', ['name' => trans('programs::excursions.title.excursions')]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Excursion $excursion
     * @return Response
     */
    public function edit(Excursion $excursion)
    {
        $types = $this->type->all()->pluck('name', 'id')->toArray();
        $features = $this->feature->all()->pluck('name', 'id')->toArray();
        return view('programs::admin.excursions.edit', compact('excursion', 'types', 'features'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Excursion $excursion
     * @param  UpdateExcursionRequest $request
     * @return Response
     */
    public function update(Excursion $excursion, UpdateExcursionRequest $request)
    {
        $this->excursion->update($excursion, $request->all());

        return redirect()->route('admin.programs.excursion.index')
            ->withSuccess(trans('core::core.messages.resource updated', ['name' => trans('programs::excursions.title.excursions')]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Excursion $excursion
     * @return Response
     */
    public function destroy(Excursion $excursion)
    {
        $this->excursion->destroy($excursion);

        return redirect()->route('admin.programs.excursion.index')
            ->withSuccess(trans('core::core.messages.resource deleted', ['name' => trans('programs::excursions.title.excursions')]));
    }
}

Modules/Programs/Resources/views/admin/excursions/partials/create-fields.blade.php
<div class="form-group {{ $errors->has("time") ? ' has-error' : '' }}">
    {!! Form::label("time", trans('programs::excursions.form.time')) !!}
    {!! Form::text("time", old("time"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.time')]) !!}
    {!! $errors->first("time", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("duration") ? ' has-error' : '' }}">
    {!! Form::label("duration", trans('programs::excursions.form.duration')) !!}
    {!! Form::number("duration", old("duration"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.duration')]) !!}
    {!! $errors->first("duration", '<span class="help-block">:message</span>') !!}
</div>

{!! Form::normalSelect('type_id', trans('programs::excursions.form.type'), $errors, $types, null, ['class' => '']) !!}
{!! Form::normalSelect('dates', trans('programs::excursions.form.dates'), $errors, [], null, ['class' => '', 'multiple' => 'multiple']) !!}
{!! Form::normalSelect('features', trans('programs::excursions.form.features'), $errors, $features, null, ['class' => '', 'multiple' => 'multiple']) !!}

<div class="row">
    <div class="col-md-3 col-sm-4">
        @mediaMultiple('excursionImage', null, null, trans('programs::excursions.form.photo'))
    </div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-4">
        @mediaSingle('excursionPdf', null, null, 'PDF')
    </div>
</div>

Modules/Programs/Resources/views/admin/excursions/partials/create-trans-fields.blade.php
<div class="form-group {{ $errors->has("{$lang}[name]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[name]", trans('programs::excursions.form.name')) !!}
    {!! Form::text("{$lang}[name]", old("{$lang}[name]"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.name')]) !!}
    {!! $errors->first("{$lang}[name]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[description]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[description]", trans('programs::excursions.form.description')) !!}
    {!! Form::textarea("{$lang}[description]", old("{$lang}[description]"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.description')]) !!}
    {!! $errors->first("{$lang}[description]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[guide]") ? ' has-error' : '' }}">
    @if($lang == 'en')
        @foreach(['Guide', 'Guides'] as $caption)
            <label><input type="radio" name="{{$lang}}[guide_caption]" class="flat-blue" value="{{ $caption }}" {{$loop->first ? 'checked' : ''}}> {{$caption}}</label>
        @endforeach
    @else
        @foreach(['Ведучий', 'Ведуча', 'Ведучі'] as $caption)
            <label><input type="radio" name="{{$lang}}[guide_caption]" class="flat-blue" value="{{ $caption }}" {{$loop->first ? 'checked' : ''}}> {{$caption}}</label>
        @endforeach
    @endif
    {!! Form::text("{$lang}[guide]", old("{$lang}[guide]"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.guide')]) !!}
    {!! $errors->first("{$lang}[guide]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[max_group]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[max_group]", trans('programs::excursions.form.max_group')) !!}
    {!! Form::text("{$lang}[max_group]", old("{$lang}[max_group]"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.max_group')]) !!}
    {!! $errors->first("{$lang}[max_group]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[category]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[category]", trans('programs::excursions.form.category')) !!}
    {!! Form::text("{$lang}[category]", old("{$lang}[category]"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.category')]) !!}
    {!! $errors->first("{$lang}[category]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[phone]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[phone]", trans('programs::excursions.form.phone')) !!}
    {!! Form::text("{$lang}[phone]", old("{$lang}[phone]"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.phone')]) !!}
    {!! $errors->first("{$lang}[phone]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[price]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[price]", trans('programs::excursions.form.price')) !!}
    {!! Form::text("{$lang}[price]", old("{$lang}[price]"), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.price')]) !!}
    {!! $errors->first("{$lang}[price]", '<span class="help-block">:message</span>') !!}
</div>

Modules/Programs/Resources/views/admin/excursions/partials/edit-fields.blade.php
<div class="form-group {{ $errors->has("time") ? ' has-error' : '' }}">
    {!! Form::label("time", trans('programs::excursions.form.time')) !!}
    {!! Form::text("time", old("time", $excursion->time), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.time')]) !!}
    {!! $errors->first("time", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("duration") ? ' has-error' : '' }}">
    {!! Form::label("duration", trans('programs::excursions.form.duration')) !!}
    {!! Form::number("duration", old("duration", $excursion->duration), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.duration')]) !!}
    {!! $errors->first("duration", '<span class="help-block">:message</span>') !!}
</div>

{!! Form::normalSelect('type_id', trans('programs::excursions.form.type'), $errors, $types, $excursion, ['class' => '']) !!}
{!! Form::normalSelect('dates', trans('programs::excursions.form.dates'), $errors, $excursion->form_dates, $excursion, ['class' => '', 'multiple' => 'multiple']) !!}
{!! Form::normalSelect('features', trans('programs::excursions.form.features'), $errors, $features, $excursion, ['class' => '', 'multiple' => 'multiple']) !!}

<div class="row">
    <div class="col-md-3 col-sm-4">
        @mediaMultiple('excursionImage', $excursion, null, trans('programs::excursions.form.photo'))
    </div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-4">
        @mediaSingle('programPdf', $excursion, null, 'PDF')
    </div>
</div>

Modules/Programs/Resources/views/admin/excursions/partials/edit-trans-fields.blade.php
<div class="form-group {{ $errors->has("{$lang}[name]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[name]", trans('programs::excursions.form.name')) !!}
    <?php $old = $excursion->hasTranslation($lang) ? $excursion->translate($lang)->name : '' ?>
    {!! Form::text("{$lang}[name]", old("{$lang}[name]", $old), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.name')]) !!}
    {!! $errors->first("{$lang}[name]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[description]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[description]", trans('programs::excursions.form.description')) !!}
    <?php $old = $excursion->hasTranslation($lang) ? $excursion->translate($lang)->description : '' ?>
    {!! Form::textarea("{$lang}[description]", old("{$lang}[description]", $old), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.description')]) !!}
    {!! $errors->first("{$lang}[description]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[guide]") ? ' has-error' : '' }}">
    @if($lang == 'en')
        @foreach(['Guide', 'Guides'] as $caption)
            <label><input type="radio" name="{{$lang}}[guide_caption]" class="flat-blue" value="{{ $caption }}" {{$excursion->guide_caption == $caption ? 'checked' : ''}}> {{$caption}}</label>
        @endforeach
    @else
        @foreach(['Ведучий', 'Ведуча', 'Ведучі'] as $caption)
            <label><input type="radio" name="{{$lang}}[guide_caption]" class="flat-blue" value="{{ $caption }}" {{$excursion->guide_caption == $caption ? 'checked' : ''}}> {{$caption}}</label>
        @endforeach
    @endif
    <?php $old = $excursion->hasTranslation($lang) ? $excursion->translate($lang)->guide : '' ?>
    {!! Form::text("{$lang}[guide]", old("{$lang}[guide]", $old), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.guide')]) !!}
    {!! $errors->first("{$lang}[guide]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[max_group]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[max_group]", trans('programs::excursions.form.max_group')) !!}
    <?php $old = $excursion->hasTranslation($lang) ? $excursion->translate($lang)->max_group : '' ?>
    {!! Form::text("{$lang}[max_group]", old("{$lang}[max_group]", $old), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.max_group')]) !!}
    {!! $errors->first("{$lang}[max_group]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[category]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[category]", trans('programs::excursions.form.category')) !!}
    <?php $old = $excursion->hasTranslation($lang) ? $excursion->translate($lang)->category : '' ?>
    {!! Form::text("{$lang}[category]", old("{$lang}[category]", $old), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.category')]) !!}
    {!! $errors->first("{$lang}[category]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[phone]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[phone]", trans('programs::excursions.form.phone')) !!}
    <?php $old = $excursion->hasTranslation($lang) ? $excursion->translate($lang)->phone : '' ?>
    {!! Form::text("{$lang}[phone]", old("{$lang}[phone]", $old), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.phone')]) !!}
    {!! $errors->first("{$lang}[phone]", '<span class="help-block">:message</span>') !!}
</div>

<div class="form-group {{ $errors->has("{$lang}[price]") ? ' has-error' : '' }}">
    {!! Form::label("{$lang}[price]", trans('programs::excursions.form.price')) !!}
    <?php $old = $excursion->hasTranslation($lang) ? $excursion->translate($lang)->price : '' ?>
    {!! Form::text("{$lang}[price]", old("{$lang}[price]", $old), ["class" => "form-control", "placeholder" => trans('programs::excursions.form.price')]) !!}
    {!! $errors->first("{$lang}[price]", '<span class="help-block">:message</span>') !!}
</div>